# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='upload/')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='since',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='to',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
