# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_auto_20171210_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='title',
            field=models.CharField(default='dyfolt', max_length=200),
            preserve_default=False,
        ),
    ]
