# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_remove_file_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.ImageField(upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='picture',
            field=models.ImageField(upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='picture',
            field=models.ImageField(upload_to='news/'),
        ),
    ]
